Feature/applicant openings backbutton
Monash-FIT3170/Onboarder pull request #100
Opened 2024-10-05 15:59 UTC by umairBinMohammad

Back button for applicants page.

2024-10-05 16:01 UTC, Khang0018 approved these changes
LGTM

2024-10-06 03:45 UTC, jcru0005 requested changes

2024-10-06 03:45 UTC, jcru0005 commented on frontend/src/screens/ApplicantOpenings.tsx
> +
Why is this here?

2024-10-06 03:57 UTC, jcru0005 commented on frontend/src/screens/ApplicantOpenings.tsx
> +
If it was because you cannot access login page while logged in, we will have to do another fix instead of logging user out

2024-10-06 10:32 UTC, HanifZafari approved these changes
LGTM

2024-10-06 10:33 UTC, jcru0005 approved these changes

2024-10-06 10:33 UTC, merged