Implement Role-Based Access Control (RBAC) using CASL
Monash-FIT3170/Onboarder pull request #107
Opened 2024-10-09 08:23 UTC by HanifZafari

# Implement Role-Based Access Control (RBAC)

## Description

This pull request implements Role-Based Access Control (RBAC) system using the CASL library (@casl/ability and @casl/react). The changes introduce fine-grained permissions based on user roles.

### Key Changes:

1. **Dependency Updates**: 
   - Updated package dependencies for @casl/ability and @casl/react

2. **CASL Implementation**:
   - Added ability definitions for different user roles in abilities
   - Updated the auth store to set abilities based on user's role whenever a team is changed. 

3. **UI Updates**:
   - Created a new PermissionButton component for handling permissions and rendering buttons based on user's ability
   - Used the PermissionButton to replace normal buttons wherever RBAC required.

## Testing Instructions

Please test the following scenarios:

1. Log in with different user roles and verify that UI elements (especially buttons) are correctly shown/hidden based on permissions.
2. Attempt to perform actions with different user roles to ensure that permissions are correctly enforced.
 
## Additional Notes

- Abilities can be found in ./frontend/util/abilities.ts, this is where all the abilities for each user role is defined.

2024-10-10 02:47 UTC, JesseCr00 requested changes
Looks good, just need a few minor changes.

2024-10-10 02:47 UTC, JesseCr00 commented on frontend/src/screens/AddRecruitmentRoundPage.tsx
This page needs a permission button on Submit too

2024-10-10 02:47 UTC, JesseCr00 commented on frontend/src/screens/AdminAcceptPage.tsx
Maybe don't need permissions on here. It's fine to keep it, just make sure all roles have this permission. (Might limit in future)

2024-10-10 02:47 UTC, JesseCr00 commented on frontend/src/util/abilities.ts
Do owners and admins have all the permissions that team lead does?

2024-10-10 02:47 UTC, JesseCr00 commented on frontend/src/screens/FeedbackNote.tsx
For the permission buttons here, again can Admin and Owner do it as well?

2024-10-10 02:47 UTC, JesseCr00 commented on frontend/src/screens/ViewRecruitmentRoundPage.tsx
> +            <PermissionButton
I think let them open the modal, but dont let them edit or save.

2024-10-11 10:17 UTC, JesseCr00 approved these changes

2024-10-11 10:39 UTC, Rahul-Saxena-1 approved these changes

2024-10-12 02:23 UTC, merged